### ISSUE TITLE
Strange behavior of attribute writers

### ISSUE THREAD

**Issue by roysc** [mdub/clamp#70]
Not sure if I'm crazy or if this is doing the wrong thing:
```ruby
require 'clamp'

class WeirdCommand < Clamp::Command
  DEFAULT_FOO = 'fo0'

  parameter 'FOO', 'The foo', required: false

  def execute
    unless foo
      foo = DEFAULT_FOO         # Fails
      # @foo = DEFAULT_FOO      # Works
    end

    bar(foo)
  end

  def bar(f)
    puts %(The foo is "#{f}")
  end
end

RSpec.describe WeirdCommand do
  subject(:weird) do
    described_class.new('weird', {})
      .tap { |c| c.parse(args) }
  end
  let(:args) { [] }

  describe '#execute' do
    context 'without foo' do
      it 'bars the foo' do
        expect(subject).to receive(:bar).with(described_class::DEFAULT_FOO)
        subject.execute
      end
    end

    context 'with foo' do
      let(:foo_arg) { 'quux' }
      let(:args) { [foo_arg] }

      it 'bars the foo' do
        expect(subject).to receive(:bar).with(foo_arg)
        subject.execute
      end
    end
  end
end
```

Running spec:
```
$ rspec test_case.rb --format doc --color

WeirdCommand
  #execute
    without foo
      bars the foo
    with foo
      bars the foo (FAILED - 1)

Failures:

  1) WeirdCommand#execute with foo bars the foo
     Failure/Error: bar(foo)
     
       #<WeirdCommand:0x007fbd5391f178 @invocation_path="weird", @context={}, @remaining_arguments=[], @foo="quux"> received :bar with unexpected arguments
         expected: ("quux")
              got: (nil)
       Diff:
       @@ -1,2 +1,2 @@
       -["quux"]
       +[nil]
       
     # ./test_case.rb:13:in `execute'
     # ./test_case.rb:42:in `block (4 levels) in <top (required)>'

Finished in 0.02258 seconds (files took 0.12948 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./test_case.rb:40 # WeirdCommand#execute with foo bars the foo
```

The behavior of the command seems to be affected by a call to `foo=()` when that line should not even be reached, i.e., when `foo` is passed as a parameter (the `unless` block should not run, but `foo` is set to nil). Replace the call with a direct `@foo = ` and the issue goes away.

I've been staring at this for a while and I don't see how it's possible. Please tell me what I'm doing wrong.

**Comment by mdub** [comment]
I think that the `# Fails` line creates a method-local variable "foo", which shadows the "foo" attribute. And you're passing the local-variable (not the attribute) to "bar".

**Comment by roysc** [comment]
Ah. So the _parser_ will force a local `foo` to be declared (and set to nil), regardless of whether the block actually runs.

Man, I hate Ruby sometimes.

**Comment by wesm-outreach** [comment]
also, the clamp README shows how to set complex default values also
```
def default_foo
  'fo0'.freeze
end
```

**Comment by wesm-outreach** [comment]
sorry, I was commenting on what you were _trying_ to do instead of the ruby specific issue. This is the no.1 issue I have with ruby. I can't tell if I'm calling a instance method or using a local variable.

**Comment by roysc** [comment]
Agreed, Ruby likes to confuse its users.

And speaking of which, this is actually still bothering me. If I explicitly define `foo=()`:
```
  def foo=(x)
    STDERR.puts "setting foo to (#{x})"
    @foo = x
  end
```

And run the spec:
```
$ rspec test_case.rb --format doc --color

WeirdCommand
  #execute
    without foo
      bars the foo
    with foo
setting foo to (quux)
      bars the foo (FAILED - 1)

Failures:

  1) WeirdCommand#execute with foo bars the foo
     Failure/Error: bar(foo)
     
       #<WeirdCommand:0x007fa841a3c4b0 @invocation_path="weird", @context={}, @remaining_arguments=[], @foo="quux"> received :bar with unexpected arguments
         expected: ("quux")
              got: (nil)
       Diff:
       @@ -1,2 +1,2 @@
       -["quux"]
       +[nil]
       
     # ./test_case.rb:14:in `execute'
     # ./test_case.rb:48:in `block (4 levels) in <top (required)>'

Finished in 0.01431 seconds (files took 0.10371 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./test_case.rb:46 # WeirdCommand#execute with foo bars the foo
```

That writer method is defined and is being called, so at parse and run time, a new local variable should not be getting initialized. Yet the behavior doesn't change.
